"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Topbar from "@/components/Topbar";
import Modal from "@/components/Modal";
import { api } from "@/lib/api";

export default function KnowledgePage(){
 const [graph,setGraph]=useState<any>({nodes:[],edges:[]}); const [entities,setEntities]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [showAdd,setShowAdd]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
 function load(){Promise.all([api<any>("/api/v1/knowledge/graph?limit=45"),api<any[]>("/api/v1/knowledge/entities?limit=150")]).then(([g,e])=>{setGraph(g);setEntities(e)}).catch(e=>setError(e.message))} useEffect(load,[]);
 async function enrich(){try{const r:any=await api("/api/v1/knowledge/enrich-all",{method:"POST"});setNotice(`Queued ${r.queued} memories for graph enrichment.`)}catch(e:any){setError(e.message)}}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/v1/knowledge/entities",{method:"POST",body:JSON.stringify({name:f.get("name"),entity_type:f.get("entity_type")||"other",description:f.get("description"),aliases:String(f.get("aliases")||"").split(",").map(x=>x.trim()).filter(Boolean)})});setShowAdd(false);load()}catch(e:any){setError(e.message)}}
 async function open(id:string){try{setSelected(await api(`/api/v1/knowledge/entities/${id}`))}catch(e:any){setError(e.message)}}
 const pos=useMemo(()=>{const m=new Map<string,{x:number,y:number}>();const nodes=graph.nodes||[];nodes.forEach((n:any,i:number)=>{const ring=i===0?0:i<13?1:2;const idx=ring===0?0:ring===1?i-1:i-13;const total=ring===0?1:ring===1?Math.min(Math.max(nodes.length-1,1),12):Math.max(nodes.length-13,1);const a=ring===0?0:Math.PI*2*idx/total-Math.PI/2;const r=ring===0?0:ring===1?145:245;m.set(n.id,{x:350+Math.cos(a)*r,y:280+Math.sin(a)*r})});return m},[graph]);
 return <><Topbar eyebrow="Knowledge core" title="Entity Graph" />{error&&<div className="errorBox">{error}</div>}{notice&&<div className="successBox">{notice}</div>}
 <div className="row" style={{justifyContent:"space-between",marginBottom:14}}><div className="meta">Stable entities and relationships extracted from your memories.</div><div className="row"><button className="ghostButton" onClick={()=>setShowAdd(true)}>+ Entity</button><button className="button primary" onClick={enrich}>Enrich all memories</button></div></div>
 <div className="split"><section className="panel" style={{marginTop:0}}><div className="panelHead"><h2>Relationship map</h2><span className="meta">{graph.nodes?.length||0} nodes · {graph.edges?.length||0} edges</span></div><div className="graphCanvas"><svg viewBox="0 0 700 560">
 {(graph.edges||[]).map((e:any)=>{const a=pos.get(e.from_entity_id),b=pos.get(e.to_entity_id);if(!a||!b)return null;return <g key={e.id}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="graphEdge"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2} className="graphEdgeLabel">{e.relation_type}</text></g>})}
 {(graph.nodes||[]).map((n:any)=>{const p=pos.get(n.id);if(!p)return null;const r=18+Math.min(Number(n.memory_count||0),7)*2;return <g key={n.id} className="graphNode" onClick={()=>open(n.id)}><circle cx={p.x} cy={p.y} r={r}/><text x={p.x} y={p.y+4} textAnchor="middle" className="graphNodeType">{String(n.entity_type).slice(0,3).toUpperCase()}</text><text x={p.x} y={p.y+r+13} textAnchor="middle">{String(n.name).slice(0,22)}</text></g>})}
 </svg>{!graph.nodes?.length&&<div className="empty">No graph yet. Run enrichment first.</div>}</div></section>
 <section className="panel" style={{marginTop:0}}><div className="panelHead"><h2>Entities</h2><span className="meta">{entities.length}</span></div><div className="entityList">{entities.map((e:any)=><button className="entityRow" key={e.id} onClick={()=>open(e.id)}><span><strong>{e.name}</strong><small>{e.entity_type}</small></span><span>{e.memory_count}</span></button>)}</div></section></div>
 {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)}><div className="row"><span className="badge">{selected.entity_type}</span><span className="meta">{(selected.aliases||[]).join(", ")}</span></div>{selected.description&&<p className="memoryContent">{selected.description}</p>}<h3>Relationships</h3>{(selected.relations||[]).map((r:any)=><div className="entityRelation" key={r.id}><span className="badge">{r.relation_type}</span> {r.from_name} → {r.to_name}</div>)}<h3>Linked memories</h3>{(selected.memories||[]).map((m:any)=><a className="entityMemory" href={`/memories/${m.id}`} key={m.id}><strong>{m.title}</strong><span>{m.memory_type} · {m.importance}/10</span></a>)}</Modal>}
 {showAdd&&<Modal title="Create entity" onClose={()=>setShowAdd(false)}><form className="formGrid" onSubmit={add}><div className="field full"><label>Name</label><input className="input" name="name" required/></div><div className="field"><label>Type</label><input className="input" name="entity_type" defaultValue="other"/></div><div className="field"><label>Aliases</label><input className="input" name="aliases"/></div><div className="field full"><label>Description</label><textarea className="textarea" name="description"/></div><div className="field full row" style={{justifyContent:"flex-end"}}><button className="button primary">Create</button></div></form></Modal>}
 </>;
}
